In [14]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [7]:
import sys
sys.path.remove('/home/alex/my python/prak/lab1')

In [10]:
from importlib import reload
sys.path.append('/home/alex/my python/prak/lab1/ee')
sys.path

['',
 '/home/alex/anaconda3/lib/python34.zip',
 '/home/alex/anaconda3/lib/python3.4',
 '/home/alex/anaconda3/lib/python3.4/plat-linux',
 '/home/alex/anaconda3/lib/python3.4/lib-dynload',
 '/home/alex/anaconda3/lib/python3.4/site-packages',
 '/home/alex/anaconda3/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg',
 '/home/alex/anaconda3/lib/python3.4/site-packages/cryptography-0.9.1-py3.4-linux-i686.egg',
 '/home/alex/anaconda3/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg',
 '/home/alex/anaconda3/lib/python3.4/site-packages/IPython/extensions',
 '/home/alex/my python/prak/lab1/ee']

In [98]:
def func():
    for i in range(10):
        i*i
    return i

%timeit func()

The slowest run took 4.15 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.46 µs per loop


# Testing 1 exersize

In [19]:
import exersize1 as ex1

In [24]:
t1 = np.random.randint(20, size = (10, 10))
t2 = np.random.randint(-10, 10, size = (50, 50))
t3 = np.random.randint(10, size = (100, 100))
t4 = np.random.randint(10, size = (500, 500))
t5 = np.random.randint(10, size = (1000, 1000))
test_list =[t1, t2, t3, t4, t5]

In [25]:
import time
reload(ex1)
vec = np.zeros((5))
non_vec = np.zeros((5))
extra = np.zeros((5))
x = np.zeros((5))
timer = np.zeros((3))
for i in range(len(test_list)):
    x[i] = test_list[i].shape[0]
    for j in range(10000//((i+1)**3)):
        start = time.time()
        ex1.var_vec(test_list[i])
        end = time.time()
        timer[0] += end - start
    
        start = time.time()
        ex1.var_non_vec(test_list[i])
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        ex1.var_extra(test_list[i])
        end = time.time()
        timer[2] += end - start
    timer /= j + 1
    #print(end-start, j)
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]


In [26]:
vec

array([  1.11791611e-05,   1.13441255e-05,   1.16764408e-05,
         1.62414626e-05,   2.52131272e-05])

In [27]:
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
plt.title("Speeds of algorithms in 1th exersize")
plt.xlabel('elements on diagonal of array')
plt.ylabel('time, s')
plt.legend(['Vectorized variant', 'Non vectorized variant', 'Mixed variant'], loc='upper left')
plt.show()
#plt.imsave('/home/alex/my python/prak/lab1/foto', format = 'pdf')

## Testint ex2

In [115]:
import exersize2 as ex2


In [130]:
max_size1 = 50
size1 = np.array([10, 50, 100, 200])
x1 = []
y1 = []
X = np.random.rand(max_size1, max_size1)
for i in range(size1.size):
    x1 += [np.random.randint(0, max_size1, size = (size1[i]))]
    y1 += [np.random.randint(0, max_size1, size = (size1[i]))]


In [132]:
reload(ex2)
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))
#x = np.zeros((size1.size))
for i in range(size1.size):
    for j in range(10000//((i+1)**3)):
        start = time.time()
        ex2.var_vec(X, x1[i], y1[i])
        end = time.time()
        timer[0] += (end - start)
    
        start = time.time()
        ex2.var_non_vec(X, x1[i], y1[i])
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        ex2.var_extra(X, x1[i], y1[i])
        end = time.time()
        timer[2] += end - start
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

In [134]:
vec

array([  5.19151688e-06,   5.56197639e-06,   6.62889263e-06,
         8.38408652e-06])

In [135]:
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
#plt.legend((vec, non_vec, extra), ("Vectorized variant", "Non vectorized variant", "Variant with list comprehensoin"))
plt.show()

In [52]:
max_size1 = 1000
size1 = np.array([10, 50, 100, 200])
x1 = []
y1 = []
X = np.random.rand(max_size1, max_size1)
for i in range(size1.size):
    x1 += [np.random.randint(0, max_size1, size = (size1[i]))]
    y1 += [np.random.randint(0, max_size1, size = (size1[i]))]


In [53]:
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))
#x = np.zeros((size1.size))
for i in range(size1.size):
    for j in range(3000//((i+1)**3)):
        start = time.time()
        ex2.var_vec(X, x1[i], y1[i])
        end = time.time()
        timer[0] += end - start
    
        start = time.time()
        ex2.var_non_vec(X, x1[i], y1[i])
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        ex2.var_extra(X, x1[i], y1[i])
        end = time.time()
        timer[2] = end - start
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

In [54]:
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')

plt.show(graf)

# Testing ex3

In [55]:
import exersize3 as ex3

In [159]:
max_size = np.array([10, 100, 1000, 10000, 100000])
multi_a = []
multi_a2 = [] #same multisets
multi_b = [] #diff var
for i in max_size:
    matrix = np.random.randint(10, size = (i))
    multi_a += [matrix]
    matrix = np.reshape(matrix, (5, -1))
    matrix = np.roll(matrix, 3, axis = 1)
    matrix = np.reshape(matrix, (-1))
    multi_a2 += [matrix]
    multi_b += [np.random.randint(10, size = (i))]
    




In [160]:
print(multi_a[0], multi_a2[0])

[3 5 2 9 2 9 3 9 6 6] [5 3 9 2 9 2 9 3 6 6]


In [161]:
size1 = max_size
check = np.zeros((4, 2), dtype = bool)
vec = np.zeros((size1.size, 2))
non_vec = vec.copy()
extra = vec.copy()
extra2 = vec.copy()
timer = np.zeros((4,2))
#x = np.zeros((size1.size))
for i in range(size1.size):
    for j in range(5000//((i+1)**3)):
        # var vec
        start = time.time()
        check[0, 0] = ex3.var_vec(multi_a[i], multi_b[i])
        end = time.time()
        timer[0, 0] += end - start
        
        start = time.time()
        check[0, 1] = ex3.var_vec(multi_a[i], multi_a2[i])
        end = time.time()
        timer[0, 1] += end - start
    
        # var non vec
        start = time.time()
        check[1, 0] += ex3.var_non_vec(multi_a[i], multi_b[i])
        end = time.time()
        timer[1, 0] += end - start
        
        start = time.time()
        check[1, 1] = ex3.var_non_vec(multi_a[i], multi_a2[i])
        end = time.time()
        timer[1, 1] += end - start
        
        #var extra 1
        start = time.time()
        check[2, 0] = ex3.var_extra(multi_a[i], multi_b[i])
        end = time.time()
        timer[2, 0] += end - start
        
        start = time.time()
        check[2, 1] = ex3.var_extra(multi_a[i], multi_a2[i])
        end = time.time()
        timer[2, 1] += end - start
        
        # var extra 2
        start = time.time()
        check[3, 0] = ex3.var_extra2(multi_a[i], multi_b[i])
        end = time.time()
        timer[3, 0] += end - start
        
        start = time.time()
        check[3, 1] = ex3.var_extra2(multi_a[i], multi_a2[i])
        end = time.time()
        timer[3, 1] += end - start
        
    timer /= j + 1
    vec[i, :] = timer[0, :]
    non_vec[i, :] = timer[1, :]
    extra[i, :] = timer [2, :]
    extra2[i, :] = timer [3, :]
    print(check)
    if (check[:,0]).any() or not((check[:,1]).all()):
        print(i, "problems")


[[False  True]
 [False  True]
 [False  True]
 [False  True]]
[[False  True]
 [False  True]
 [False  True]
 [False  True]]
[[False  True]
 [False  True]
 [False  True]
 [False  True]]
[[False  True]
 [False  True]
 [False  True]
 [False  True]]
[[False  True]
 [False  True]
 [False  True]
 [False  True]]


In [167]:
x = max_size

In [168]:
plt.plot(x, vec[:,1], 'rp-', x, non_vec[:,1],'bp-', x, extra[:,1], 'gp-', x, extra2[:,1], 'yp-')
plt.show()

In [155]:
start = time.time()
check[0, 0] = ex3.var_vec(multi_a[0], multi_b[0])
end = time.time()
end - start

0.0007450580596923828

# Testing exersize 4

In [29]:
import exersize4 as ex4

In [30]:
sizes = np.array([10, 100, 1000, 10000, 100000])
size1 = sizes
mass = []
for i in range(sizes.size):
    arr = np.random.randint(2**20, size = (sizes[i]))
    x = np.random.randint(sizes[i], size = (sizes[i]//4 * 3))
    arr[x] = 0
    mass += [arr]

In [31]:
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))
max_el = np.zeros((3))
#x = np.zeros((size1.size))
for i in range(size1.size):
    for j in range(10000//((i+1)**3)):
        start = time.time()
        max_el[0] = ex4.var_vec(mass[i])
        end = time.time()
        timer[0] += (end - start)
    
        start = time.time()
        max_el[1] = ex4.var_non_vec(mass[i])
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        max_el[2] = ex4.var_extra(mass[i])
        end = time.time()
        timer[2] += end - start
    if max_el[0] != max_el[1] or max_el[1] != max_el[2]:
        print("mistake")
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

In [33]:
x = sizes
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
plt.title("Speeds of algorithms in 4th exersize")
plt.xlabel('elements on diagonal of array')
plt.ylabel('time, s')
plt.legend(['Vectorized variant', 'Non vectorized variant', 'Mixed variant'], loc='upper left')
plt.show()

# Testing exersize 5

In [179]:
import exersize5 as ex5

In [183]:
sizes = np.array([100, 250, 500, 1000])
size1 = sizes
mass = []
for i in range(sizes.size):
    arr = np.random.randint(2**20, size = (sizes[i], sizes[i]+100, 3))
    mass += [arr]

In [184]:
reload(ex5)
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))

#x = np.zeros((size1.size))
for i in range(size1.size):
    for j in range(100//((i+1)**2)):
        start = time.time()
        ex5.var_vec(mass[i])
        end = time.time()
        timer[0] += (end - start)
    
        start = time.time()
        ex5.var_non_vec(mass[i])
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        ex5.var_extra(mass[i])
        end = time.time()
        timer[2] += end - start
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

In [186]:
x = sizes
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
plt.show()

/home/alex/anaconda3/lib/python3.4/site-packages/matplotlib/axes/_axes.py:475: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


AttributeError: 'NoneType' object has no attribute 'draggable'

AttributeError: 'NoneType' object has no attribute 'draggable'

# Testing exersize 6

In [187]:
import exersize6 as ex6

In [224]:
dif_vals = np.array([10, 100, 1000, 10000])
dif_vals = dif_vals//5
mass = []
for i in range(dif_vals.size):
    vals = np.random.randint(10, size = (dif_vals[i]))
    reps = np.random.randint(1, 10, size = (dif_vals[i]))
    #print(vals, reps)
    mass += [np.repeat(vals, reps)]


In [238]:
a = mass[1]
a.shape

(91,)

In [233]:
reload(ex6)
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))

#x = np.zeros((size1.size))
for i in range(size1.size):
    for j in range(1000//((i+1)**3)):
        #print(mass[i])
        start = time.time()
        a, a1 = ex6.var_vec(mass[i])
        end = time.time()
        timer[0] += (end - start)
    
        #print(mass[i])
        start = time.time()
        b, b1 = ex6.var_non_vec(mass[i])
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        c, c1 = ex6.var_extra(mass[i])
        end = time.time()
        timer[2] += end - start
    if  not np.all(a == b) or not np.all(a == c):
        print("problems", i)
    if  not np.all(a1 == b1) or not np.all(a1 == c1):
        print("problems2", i)
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

In [244]:
x = np.empty((4))
j = 0
for i in mass:
    x[j] = i.size
    j+=1
    print(i.size)
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
plt.show(graf)


8
91
1011
9847


# testing exersize7

In [11]:
import exersize7 as ex7

In [5]:
signs = np.array([10, 20, 50, 100])
obj_x = np.array([10, 40, 100, 200])
obj_y = obj_x + 20
mass = []
for i in range(signs.size):
    X = np.random.rand(obj_x[i], signs[i])
    Y = np.random.rand(obj_y[i], signs[i])
    mass += [X, Y]
    print(X.shape, Y.shape)
    

NameError: name 'mass' is not defined

In [15]:
reload(ex7)
signs = np.array([10, 20, 50, 100])
obj_x = np.array([10, 40, 100, 200])
obj_y = obj_x + 20
size1 = signs
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))
#x = np.zeros((size1.size))
for i in np.arange(size1.size):
    X = np.random.rand(obj_x[i], signs[i])
    Y = np.random.rand(obj_y[i], signs[i])
    for j in range(1000//((i+1)**3)):
        start = time.time()
        a = ex7.var_vec(X,Y)
        end = time.time()
        timer[0] += (end - start)
    
        start = time.time()
        b = ex7.var_non_vec(X,Y)
        end = time.time()
        timer[1] += end - start
        
        start = time.time()
        c = ex7.var_extra(X,Y)
        end = time.time()
        timer[2] += end - start
    if  not (a == b).all() or not(a == c).all():
        print("problems", i)
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

problems 0
problems 1
problems 2
problems 3


In [16]:
x = signs * obj_x * obj_y
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
plt.show()

In [277]:
X = mass[0]
Y = mass[1]
print(ex7.var_vec(X,Y)[0,:]- ex7.var_extra(X,Y)[0,:] )
print(ex7.var_extra(X,Y)[0,:] - ex7.var_non_vec(X,Y)[0,:])


[  0.00000000e+00   0.00000000e+00   0.00000000e+00  -2.22044605e-16
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   2.22044605e-16   0.00000000e+00
   0.00000000e+00   0.00000000e+00   2.22044605e-16   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00  -2.22044605e-16   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00]
[  0.00000000e+00   0.00000000e+00  -2.22044605e-16   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00  -2.22044605e-16
   0.00000000e+00   0.00000000e+00  -2.22044605e-16   0.00000000e+00
   4.44089210e-16   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00  -2.22044605e-16   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+0

In [274]:
ex7.var_extra(X,Y)

array([[ 1.40670056,  1.22229258,  1.32838748,  1.31957497,  1.57111556,
         1.52973417,  1.60887569,  1.77943853,  1.75087416,  1.52395672,
         1.57671522,  1.62942809,  2.1005178 ,  1.63170467,  1.59796552,
         1.59525077,  1.44936047,  1.35663428,  1.35966161,  1.49186399,
         1.64965179,  1.24559298,  1.52810987,  1.40043051,  1.14076306,
         1.47971185,  1.47536407,  1.47199846,  1.2942792 ,  1.29437895],
       [ 1.10111067,  1.19752654,  1.57250335,  1.08456376,  1.30846651,
         1.34782461,  1.32538118,  0.89760019,  1.25941573,  1.1669428 ,
         1.32844121,  0.90197616,  1.44916753,  0.8738455 ,  1.00733087,
         0.91615202,  1.19109801,  1.21008435,  1.19785054,  0.88460323,
         1.4092127 ,  0.62937435,  1.35934152,  1.1150868 ,  1.32192992,
         1.07110288,  0.80689369,  0.94076651,  0.97252356,  1.06207266],
       [ 1.31777825,  1.05707962,  1.35844335,  1.10976478,  1.18807931,
         1.2775632 ,  1.2670575 ,  1.91218278,  1

# testing exersize8

In [34]:
import exersize8 as ex8
n = np.array([5, 10, 20, 50])
points = 40
mass = []
for i in range(n.size):
    means = np.random.rand(n[i])
    X = np.random.rand(points, n[i])
    C = np.random.rand(n[i], n[i])
    C = (C + C.T)/2
    j = np.arange(C.shape[0])
    C[j, j] = 1
    mass += [(X, m, C)]


NameError: name 'm' is not defined

In [38]:
size1 = n
vec = np.zeros((size1.size))
non_vec = np.zeros((size1.size))
extra = np.zeros((size1.size))
timer = np.zeros((3))

#x = np.zeros((size1.size))
for i in range(size1.size):
    means = np.random.rand(n[i])
    X = np.random.rand(points, n[i])
    C = np.random.rand(n[i], n[i])
    C = (C + C.T)/16
    j = np.arange(C.shape[0])
    C[j, j] = 1
    
    for j in range(1000//((i+1)**3)):
        start = time.time()
        a = ex8.var_vec(X, means, C)
        end = time.time()
        timer[0] += (end - start)
    
        start = time.time()
        b = ex8.var_non_vec(X, means, C)
        end = time.time()
        timer[1] += end - start
        
        
        start = time.time()
        c = ex8.var_extra(X, means, C)
        end = time.time()
        timer[2] += end - start
    if  not (a == b).all() or not(a == c).all():
        print("problems", a-b, b-c)
    timer /= j + 1
    vec[i] = timer[0]
    non_vec[i] = timer[1]
    extra[i] = timer [2]

problems [  0.00000000e+00  -8.88178420e-16   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00  -8.88178420e-16   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00] [ -8.88178420e-16  -8.88178420e-16  -1.77635684e-15  -1.77635684e-15
  -8.88178420e-16  -8.88178420e-16  -1.77635684e-15  -8.88178420e-16
  -1.77635684e-15  -8.88178420e-16  -1.77635684e-15  -1.77635684e-15
  -1.77635684e-15  -8.88178420e-16  -8.88178420e-16  -8.88178420e-16
  -8.88178420e-16  -1.77

In [40]:
x = n
plt.plot(x, vec, 'rp-', x, non_vec,'bp-', x, extra, 'gp-')
plt.show()